### ISSUE TITLE
Input more than just seconds

### ISSUE THREAD

**Issue by stianjensen** [stianjensen/changeplac.es#4]
Allow input of hours, minutes, seconds instead of just seconds.
Can be done in the URL by separating with a / or a -.

**Comment by sigvef** [comment]
Consider the convention used by YouTube in their start-time-marked video urls, since people might be familiar with that syntax. Example:

https://www.youtube.com/watch?v=3yGiiU8_gnE&feature=youtu.be&t=2m26s

**Comment by stianjensen** [comment]
Ah, good idea. That'll be a lot more intuituve than what I had in mind :)
